# Generated by Django 4.1.7 on 2023-02-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afternoonDjangoRegistration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
