# Generated by Django 4.1.7 on 2023-03-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afternoonDjangoRegistration', '0002_rename_products_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_name', models.CharField(max_length=30)),
                ('suo_email', models.CharField(max_length=30)),
                ('sup_phone', models.CharField(max_length=30)),
                ('sup_product', models.CharField(max_length=30)),
            ],
        ),
    ]
